[package]
name = "minilog"
version = "0.1.0"
authors = ["ac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "^0.4.14", features = ["std"] }
